# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'coffee-shops-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for coffee-shops-app
	pod 'SwiftGen', '~> 6.6.2'
	pod 'SnapKit', '~> 5.6.0'
	pod 'Moya', '~> 15.0'
	pod 'Kingfisher', '~> 7.0'
	pod 'YandexMapsMobile', '4.4.0-lite'
end
